"use client";

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import Link from 'next/link';
import { 
    FaPills, FaFlask, FaUserMd, FaHospital, FaIndustry, FaSave, FaTimes, 
    FaEdit, FaTrash, FaCheck, FaExclamationCircle, FaCrown, FaBarcode, 
    FaInbox, FaColumns, FaUpload, FaEye, FaArrowRight, FaChevronDown, 
    FaSearch, FaUtensils, FaStar 
} from "react-icons/fa";
import { HiMenuAlt2 } from "react-icons/hi";

// ===================================================================================
//  1. MEMOIZED IMAGE COMPONENT
// ===================================================================================
const MedicineImage = React.memo(({ src, alt, className, style, onError }) => {
    return (
        <img 
            src={src} 
            alt={alt} 
            className={className}
            style={style}
            onError={onError}
            loading="lazy"
        />
    );
});
MedicineImage.displayName = "MedicineImage";

// ===================================================================================
//  2. REALISTIC MOCK DATA FOR DESIGN MODE
// ===================================================================================
const initialProductsMock = [
    { 
        _id: "p1", 
        Id: "PRD001",
        name: "OneTouch Select Plus Glucometer", 
        manufacturers: "LifeScan India", 
        salt_composition: "Electro-chemical blood sugar monitoring",
        packaging: "Pack of 1 Machine & 10 Strips",
        mrp: 1200, 
        best_price: 950, 
        discont_percent: "20%",
        prescription_required: "No", 
        for_sale: "ADD TO CART",
        rating: "4.7",
        expectedDelivery: "Tomorrow",
        bread_crumb: "Devices",
        url: "https://www.diabeteswala.com",
        image_url: ["https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&auto=format&fit=crop"],
        description: "OneTouch Select Plus is a simple blood glucose monitoring system designed to help you manage your diabetes easily.",
        introduction: "An easy-to-use blood sugar testing machine with three-color target range indicator.",
        how_works: "Uses blood sample to measure glucose level via electrochemical test strips.",
        benefits: "Quick 5-second results, 3-color range indicator, stores up to 500 test results.",
        storage: "Store the machine and strips in a cool dry place.",
        use_of: "Self-monitoring of blood glucose levels",
        how_to_use: "Prick finger, put a small droplet of blood on the strip, and insert it into the machine.",
        side_effect: "None. Temporary minor pain from finger pricking.",
        safety_advise: "Read the instruction manual carefully before first use. Do not share lancets.",
        supervision: "Self-monitoring or under adult supervision.",
        if_miss: "Test as per schedule or when feeling symptoms of hypoglycemia.",
        alternate_brand: "Accu-Chek Instant, Dr. Trust Glucometer"
    },
    { 
        _id: "p2", 
        Id: "PRD002",
        name: "Accu-Chek Active Test Strips (50s)", 
        manufacturers: "Roche Diagnostics", 
        salt_composition: "Glucose dehydrogenase biosensor technology",
        packaging: "Vial of 50 test strips",
        mrp: 1050, 
        best_price: 840, 
        discont_percent: "20%",
        prescription_required: "No", 
        for_sale: "ADD TO CART",
        rating: "4.6",
        expectedDelivery: "Tomorrow",
        bread_crumb: "Consumables",
        url: "https://www.diabeteswala.com",
        image_url: ["https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&auto=format&fit=crop"],
        description: "Accu-Chek Active Test Strips are designed for quantitative blood glucose testing using Accu-Chek Active glucometer.",
        introduction: "Premium test strips for highly accurate blood sugar monitoring.",
        how_works: "A chemical reaction on the strip measures the electrical current generated by the glucose.",
        benefits: "Fills quickly with small blood droplet, double-check option for visual inspection.",
        storage: "Keep the container tightly closed. Do not freeze.",
        use_of: "In vitro diagnostic blood glucose testing",
        how_to_use: "Insert strip into the meter, apply blood sample when prompted.",
        side_effect: "None.",
        safety_advise: "Check the expiration date before testing. Discard strips after the expiry date."
    }
];

export default function MedicineProduct() {
    // Local State Management
    const [products, setProducts] = useState(initialProductsMock);
    const [sortColumn, setSortColumn] = useState('');
    const [sortDirection, setSortDirection] = useState('asc');
    const [editingRow, setEditingRow] = useState(null);
    const [editedData, setEditedData] = useState({});
    const [selectedFile, setSelectedFile] = useState(null);
    const [searchTerm, setSearchTerm] = useState('');
    const [modalShow, setModalShow] = useState(false);
    const [selectedMedicine, setSelectedMedicine] = useState(null);
    const [selectedIds, setSelectedIds] = useState([]);
    
    // Process indicators
    const [loading, setLoading] = useState(false);
    const [isDeleting, setIsDeleting] = useState(false);
    const [uploadProgress, setUploadProgress] = useState(0);

    // Royal Indigo theme styling variables
    const themeBg = "bg-[#3D3F96]";
    const themeText = "text-[#3D3F96]";
    const themeHoverBg = "hover:bg-[#2C2D75]";
    const themeBorder = "border-[#3D3F96]";
    const themeRing = "focus:ring-[#3D3F96]/30";
    const themeShadow = "shadow-[#3D3F96]/20";

    const [visibleColumns, setVisibleColumns] = useState(new Set([
        'Id', 'name', 'manufacturers', 'packaging', 'mrp', 
        'best_price', 'discont_percent', 'prescription_required','image_url', 
        'for_sale', 'actions', 'view_more'
    ]));

    const dummyImages = useMemo(() => [
        "https://images.pexels.com/photos/3873209/pexels-photo-3873209.jpeg",
        "https://images.pexels.com/photos/51929/medications-cure-tablets-pharmacy-51929.jpeg",
        "https://images.pexels.com/photos/208512/pexels-photo-208512.jpeg"
    ], []);

    const tableHeaders = useMemo(() => [
        { key: 'Id', label: 'ID', sortable: true },
        { key: 'name', label: 'Product Name', sortable: true },
        { key: 'manufacturers', label: 'Manufacturer', sortable: true },
        { key: 'salt_composition', label: 'Salt Composition', sortable: false },
        { key: 'packaging', label: 'Packaging', sortable: false },
        { key: 'mrp', label: 'MRP', sortable: true },
        { key: 'best_price', label: 'Best Price', sortable: true },
        { key: 'discont_percent', label: 'Discount %', sortable: true },
        { key: 'prescription_required', label: 'Prescription Required', sortable: true },
        { key: 'image_url', label: 'Image', sortable: false },
        { key: 'primary_use', label: 'Primary Use', sortable: false },
        { key: 'description', label: 'Description', sortable: false },
        { key: 'storage', label: 'Storage', sortable: false },
        { key: 'introduction', label: 'Introduction', sortable: false },
        { key: 'use_of', label: 'Use Of', sortable: false },
        { key: 'benefits', label: 'Benefits', sortable: false },
        { key: 'side_effect', label: 'Side Effects', sortable: false },
        { key: 'how_to_use', label: 'How to Use', sortable: false },
        { key: 'how_works', label: 'How it Works', sortable: false },
        { key: 'safety_advise', label: 'Safety Advice', sortable: false },
        { key: 'supervision', label: 'Supervision', sortable: false },
        { key: 'if_miss', label: 'If Missed', sortable: false },
        { key: 'alternate_brand', label: 'Alternate Brand', sortable: false },
        { key: 'for_sale', label: 'For Sale', sortable: true },
        { key: 'discount_seller', label: 'Discount Seller', sortable: true },
        { key: 'rating', label: 'Rating', sortable: true },
        { key: 'boughtParameter', label: 'Bought Parameter', sortable: true },
        { key: 'expectedDelivery', label: 'Expected Delivery', sortable: false },
        { key: 'popularCategory', label: 'Popular Category', sortable: true },
        { key: 'orderCount', label: 'Order Count', sortable: true },
        { key: 'bread_crumb', label: 'Category', sortable: false },
        { key: 'url', label: 'URL', sortable: false },
        { key: 'createdAt', label: 'Created At', sortable: true },
        { key: 'updatedAt', label: 'Updated At', sortable: true },
        { key: 'actions', label: 'Actions', sortable: false },
        { key: 'view_more', label: 'View More', sortable: false }
    ], []);

    const searchableFields = useMemo(() => [
        'name', 'manufacturers', 'salt_composition', 'primary_use', 
        'description', 'benefits', 'bread_crumb', 'alternate_brand'
    ], []);

    // Working search and sort inside useMemo
    const sortedProducts = useMemo(() => {
        let processedProducts = [...products];

        if (searchTerm) {
            processedProducts = processedProducts.filter(product =>
                searchableFields.some(field =>
                    product[field]?.toString().toLowerCase().includes(searchTerm.toLowerCase())
                )
            );
        }

        if (sortColumn) {
            processedProducts.sort((a, b) => {
                let aValue = a[sortColumn];
                let bValue = b[sortColumn];

                if (['mrp', 'best_price', 'rating', 'boughtParameter', 'orderCount', 'discount_seller'].includes(sortColumn)) {
                    aValue = parseFloat(aValue) || 0;
                    bValue = parseFloat(bValue) || 0;
                } else if (sortColumn === 'popularCategory') {
                    aValue = aValue ? 1 : 0;
                    bValue = bValue ? 1 : 0;
                } else if (['createdAt', 'updatedAt'].includes(sortColumn)) {
                    aValue = new Date(aValue).getTime() || 0;
                    bValue = new Date(bValue).getTime() || 0;
                } else if (typeof aValue === 'string' && typeof bValue === 'string') {
                    aValue = aValue.toLowerCase();
                    bValue = bValue.toLowerCase();
                }

                if (aValue < bValue) return sortDirection === 'asc' ? -1 : 1;
                if (aValue > bValue) return sortDirection === 'asc' ? 1 : -1;
                return 0;
            });
        }
        
        return processedProducts;
    }, [products, searchTerm, searchableFields, sortColumn, sortDirection]);

    const handleFileChange = useCallback((event) => {
        const file = event.target.files[0];
        if (file) {
            setSelectedFile(file);
        }
    }, []);

    const handleUpload = useCallback(async () => {
        if (!selectedFile) return;

        setLoading(true);
        setUploadProgress(20);
        
        // Simulating upload intervals
        const interval = setInterval(() => {
            setUploadProgress(prev => {
                if (prev >= 100) {
                    clearInterval(interval);
                    setTimeout(() => {
                        setLoading(false);
                        setUploadProgress(0);
                        setSelectedFile(null);
                        const fileInput = document.getElementById('excel-file');
                        if (fileInput) fileInput.value = '';
                        alert("Excel file uploaded successfully (Mock Mode)!");
                    }, 400);
                    return 100;
                }
                return prev + 40;
            });
        }, 400);

    }, [selectedFile]);

    const handleSort = useCallback((column) => {
        if (sortColumn === column) {
            setSortDirection(prev => prev === 'asc' ? 'desc' : 'asc');
        } else {
            setSortColumn(column);
            setSortDirection('asc');
        }
    }, [sortColumn]);

    const handleEdit = useCallback((rowId, rowData) => {
        setEditingRow(rowId);
        setEditedData({...rowData});
    }, []);

    const handleSave = useCallback(async (rowId) => {
        setLoading(true);
        setTimeout(() => {
            setProducts(prev => prev.map(p => p._id === rowId ? { ...p, ...editedData } : p));
            setEditingRow(null);
            setEditedData({});
            setLoading(false);
        }, 800);
    }, [editedData]);
    
    const handleDelete = useCallback(async (rowId) => {
        if (window.confirm('Are you sure you want to delete this product?')) {
            setIsDeleting(true);
            setTimeout(() => {
                setProducts(prev => prev.filter(p => p._id !== rowId));
                setIsDeleting(false);
            }, 800);
        }
    }, []);

    const handleCancel = useCallback(() => {
        setEditingRow(null);
        setEditedData({});
    }, []);

    const handleInputChange = useCallback((field, value) => {
        setEditedData(prev => ({ ...prev, [field]: value }));
    }, []);

    const toggleColumn = useCallback((columnKey) => {
        setVisibleColumns(prev => {
            const newVisibleColumns = new Set(prev);
            newVisibleColumns.has(columnKey) ? newVisibleColumns.delete(columnKey) : newVisibleColumns.add(columnKey);
            return newVisibleColumns;
        });
    }, []);
  
    const handleImageError = useCallback((e) => {
        e.target.src = dummyImages[0];
    }, [dummyImages]);
  
    const handleRowClick = useCallback((rowData) => {
        setSelectedMedicine(rowData);
        setModalShow(true);
    }, []);

    const handleSelectRow = useCallback((id) => {
        setSelectedIds(prev => prev.includes(id) ? prev.filter(rowId => rowId !== id) : [...prev, id]);
    }, []);

    const handleSelectAll = useCallback(() => {
        if (selectedIds.length === sortedProducts.length) {
            setSelectedIds([]);
        } else {
            setSelectedIds(sortedProducts.map(p => p._id));
        }
    }, [selectedIds.length, sortedProducts]);

    const handleDeleteSelected = useCallback(async () => {
        if (window.confirm(`Are you sure you want to delete the ${selectedIds.length} selected products?`)) {
            setIsDeleting(true);
            setTimeout(() => {
                setProducts(prev => prev.filter(p => !selectedIds.includes(p._id)));
                setSelectedIds([]);
                setIsDeleting(false);
            }, 1000);
        }
    }, [selectedIds]);

    const renderCellContent = useCallback((key, value, isEditing, rowData) => {
        if (isEditing && key !== 'Id' && key !== 'actions' && key !== 'createdAt' && key !== 'updatedAt' && key !== '_id' && key !== 'view_more') {
            switch (key) {
                case 'prescription_required':
                    return <select className="bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs" value={editedData[key] || value} onChange={(e) => handleInputChange(key, e.target.value)}><option value="Yes">Yes</option><option value="No">No</option></select>;
                case 'for_sale':
                    return <select className="bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs" value={editedData[key] || value} onChange={(e) => handleInputChange(key, e.target.value)}><option value="ADD TO CART">ADD TO CART</option><option value="OUT OF STOCK">OUT OF STOCK</option></select>;
                case 'popularCategory':
                    return <select className="bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs" value={editedData[key] !== undefined ? editedData[key] : value} onChange={(e) => handleInputChange(key, e.target.value === 'true')}><option value="true">Yes</option><option value="false">No</option></select>;
                case 'rating': case 'boughtParameter': case 'orderCount': case 'discount_seller':
                    return <input type="number" className="bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs" value={editedData[key] !== undefined ? editedData[key] : value} onChange={(e) => handleInputChange(key, e.target.value)} min="0" step={key === 'rating' ? '0.1' : '1'} />;
                case 'mrp': case 'best_price':
                    return <input type="number" className="bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs" value={editedData[key] !== undefined ? editedData[key] : value} onChange={(e) => handleInputChange(key, e.target.value)} min="0" step="0.01" />;
                case 'description': case 'introduction': case 'benefits': case 'side_effect': case 'how_to_use': case 'how_works': case 'safety_advise': case 'supervision':
                    return <textarea className="bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs w-full" value={editedData[key] !== undefined ? editedData[key] : value} onChange={(e) => handleInputChange(key, e.target.value)} rows="2" />;
                default:
                    return <input type="text" className="bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs" value={editedData[key] !== undefined ? editedData[key] : value} onChange={(e) => handleInputChange(key, e.target.value)} />;
            }
        }

        if (key === 'actions') {
            return (
                <div className="flex items-center justify-center gap-1.5" onClick={(e) => e.stopPropagation()}>
                    {isEditing ? (
                        <>
                            <button className="p-2 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-600 transition-colors" onClick={() => handleSave(rowData._id)} disabled={loading || isDeleting}>
                                {loading ? <span className="w-3.5 h-3.5 border-2 border-emerald-600 border-t-transparent rounded-full animate-spin"></span> : <FaCheck className="text-xs" />}
                            </button>
                            <button className="p-2 rounded-lg bg-gray-100 hover:bg-gray-200 text-gray-500 transition-colors" onClick={handleCancel} disabled={loading || isDeleting}><FaTimes className="text-xs" /></button>
                        </>
                    ) : (
                        <>
                            <button className="p-2 rounded-lg bg-amber-50 hover:bg-amber-100 text-amber-600 transition-colors" onClick={() => handleEdit(rowData._id, rowData)} disabled={loading || isDeleting}><FaEdit className="text-xs" /></button>
                            <button className="p-2 rounded-lg bg-rose-50 hover:bg-rose-100 text-rose-600 transition-colors" onClick={() => handleDelete(rowData._id)} disabled={loading || isDeleting}><FaTrash className="text-xs" /></button>
                        </>
                    )}
                </div>
            );
        }

        if (key === 'view_more') {
            return (
                <button className="px-3 py-1.5 rounded-lg bg-blue-50 text-blue-600 text-xs font-bold uppercase tracking-wider hover:bg-blue-100" onClick={(e) => { e.stopPropagation(); handleRowClick(rowData); }}>More Info</button>
            );
        }
        
        switch (key) {
            case 'name': return <span className="text-[#3D3F96] font-bold tracking-tight truncate block max-w-[200px]" title={value}>{value}</span>;
            case 'url': return <a href={value || '#'} className="text-[#3D3F96] hover:underline" target="_blank" rel="noopener noreferrer">Link</a>;
            case 'bread_crumb': return <span className="text-gray-400 text-xs font-medium">{value}</span>;
            case 'prescription_required': return <span className={`inline-block px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${value === 'Yes' ? 'bg-amber-50 text-amber-700 border border-amber-100' : 'bg-emerald-50 text-emerald-700 border border-emerald-100'}`}>{value === 'Yes' ? 'Required' : 'OTC'}</span>;
            case 'for_sale': return <span className={`inline-block px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${value === 'ADD TO CART' ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' : 'bg-rose-50 text-rose-700 border border-rose-100'}`}>{value}</span>;
            case 'popularCategory': return <span className={`inline-block px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${value ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-500'}`}>{value ? 'Yes' : 'No'}</span>;
            case 'discont_percent': return <span className={`inline-block px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${value === '0%' ? 'bg-indigo-50 text-[#3D3F96]' : 'bg-[#3D3F96]/10 text-[#3D3F96]'}`}>{value}</span>;
            case 'mrp': return <span className="font-black text-gray-800">₹{value}</span>;
            case 'best_price': return value === 'N/A' ? <span className="text-gray-400">{value}</span> : <span className="text-emerald-600 font-black">₹{value}</span>;
            case 'rating': return <div className="flex items-center gap-1.5"><span className="badge bg-amber-100 text-amber-800 text-xs px-2 py-0.5 rounded font-black">{value}</span><span className="text-amber-400"><FaStar /></span></div>;
            case 'expectedDelivery': return <span className="inline-block px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-sky-50 text-sky-700 border border-sky-100">{value}</span>;
            case 'orderCount': return <span className="inline-block px-2 py-0.5 rounded text-[10px] font-bold bg-[#3D3F96]/10 text-[#3D3F96]">{value}</span>;
            case 'discount_seller': return <span className="inline-block px-2 py-0.5 rounded text-[10px] font-bold bg-gray-100 text-gray-600">{value}</span>;
            case 'boughtParameter': return <span className="inline-block px-2 py-0.5 rounded text-[10px] font-bold bg-slate-800 text-white">{value}</span>;
            case 'image_url': {
                const imageUrl = Array.isArray(value) && value.length > 0 ? value[0] : dummyImages[0];
                return (
                    <div title="Click row to view details" className="inline-block relative w-9 h-9 rounded-lg overflow-hidden border border-gray-100 shadow-sm shrink-0">
                        <MedicineImage src={imageUrl} alt="Medicine" className="w-full h-full object-cover" onError={handleImageError} />
                    </div>
                );
            }
            case 'createdAt': case 'updatedAt': return <span className="text-gray-400 text-xs font-semibold">{new Date(value).toLocaleDateString()}</span>;
            case 'description': case 'introduction': case 'benefits': case 'side_effect': case 'how_to_use': case 'how_works': case 'safety_advise': case 'supervision': case 'primary_use': case 'salt_composition': case 'storage': case 'use_of': case 'if_miss': case 'alternate_brand':
                return <span className="text-truncate d-block max-w-[200px] text-xs font-semibold text-gray-500" title={value}>{value}</span>;
            default: return value || 'N/A';
        }
    }, [editedData, handleInputChange, handleSave, handleCancel, handleEdit, handleDelete, loading, isDeleting, handleImageError, dummyImages, handleRowClick]);
  
    const visibleHeaders = useMemo(() => tableHeaders.filter(header => visibleColumns.has(header.key)), [tableHeaders, visibleColumns]);

    return (
        <div className="space-y-8 max-w-7xl mx-auto px-4 py-8 select-none animate-fadeIn">
            
            {/* 1. UPLOAD PRODUCTS CARD */}
            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-[0_8px_30px_rgb(0,0,0,0.015)]">
                <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 rounded-xl bg-[#3D3F96]/10 text-[#3D3F96] flex items-center justify-center">
                        <FaUpload className="text-lg" />
                    </div>
                    <div>
                        <h2 className="text-lg font-bold text-gray-800 leading-snug">Upload Products</h2>
                        <p className="text-xs text-gray-400">Import bulk medicine product inventory via Excel spreadsheet (.xlsx, .xls)</p>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                    <div className="md:col-span-3 flex flex-col gap-1.5">
                        <label className="text-xs font-bold text-gray-500 uppercase tracking-wider">Select Excel File</label>
                        <input 
                            type="file" 
                            id="excel-file" 
                            accept=".xlsx,.xls" 
                            onChange={handleFileChange} 
                            disabled={loading}
                            className="bg-gray-50 border border-gray-200 rounded-xl px-4 py-2 text-sm text-gray-500 outline-none file:mr-4 file:py-1 file:px-3 file:rounded-md file:border-0 file:text-xs file:font-semibold file:bg-[#3D3F96]/10 file:text-[#3D3F96] hover:file:bg-[#3D3F96]/15 file:cursor-pointer transition-all focus:border-[#3D3F96]"
                        />
                    </div>
                    <button 
                        onClick={handleUpload} 
                        disabled={!selectedFile || loading}
                        className={`w-full flex items-center justify-center gap-2 text-white font-bold py-2.5 rounded-xl text-sm transition-all focus:outline-none ${themeBg} ${themeHoverBg} ${themeShadow} shadow-lg disabled:opacity-50 disabled:cursor-not-allowed`}
                    >
                        {loading && uploadProgress > 0 ? (
                            <>
                                <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
                                Uploading... {uploadProgress}%
                            </>
                        ) : "Upload File"}
                    </button>
                </div>
            </div>

            {/* 2. COLUMN VISIBILITY CARD */}
            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-[0_8px_30px_rgb(0,0,0,0.015)]">
                <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 rounded-xl bg-[#3D3F96]/10 text-[#3D3F96] flex items-center justify-center">
                        <FaColumns className="text-lg" />
                    </div>
                    <div>
                        <h2 className="text-lg font-bold text-gray-800 leading-snug">Column Visibility</h2>
                        <p className="text-xs text-gray-400">Toggle columns dynamically to customize your layout view</p>
                    </div>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
                    {tableHeaders.map((header) => (
                        <label key={header.key} className="flex items-center gap-2.5 cursor-pointer group">
                            <input 
                                type="checkbox" 
                                id={`column-${header.key}`} 
                                checked={visibleColumns.has(header.key)} 
                                onChange={() => toggleColumn(header.key)}
                                className="w-4.5 h-4.5 text-[#3D3F96] bg-gray-50 border-gray-200 rounded focus:ring-1 focus:ring-[#3D3F96]/30 cursor-pointer accent-[#3D3F96]"
                            />
                            <span className="text-xs font-semibold text-gray-600 group-hover:text-gray-900 transition-colors truncate">{header.label}</span>
                        </label>
                    ))}
                </div>
            </div>

            {/* 3. MEDICINE PRODUCTS LIST CARD */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-[0_8px_30px_rgb(0,0,0,0.015)] overflow-hidden">
                
                {/* Table Header Section */}
                <div className="flex items-center justify-between px-6 py-5 border-b border-gray-100 bg-[#3D3F96]/5 flex-wrap gap-4">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-[#3D3F96]/15 text-[#3D3F96] flex items-center justify-center">
                            <FaPills className="text-lg" />
                        </div>
                        <h2 className="text-lg font-black tracking-tight text-gray-800">
                            Medicine Products 
                            <span className="ml-2.5 px-2.5 py-0.5 rounded-full text-xs font-bold bg-[#3D3F96]/15 text-[#3D3F96]">
                                {sortedProducts.length} Registered
                            </span>
                        </h2>
                    </div>

                    <div className="flex items-center gap-3 flex-wrap">
                        {selectedIds.length > 0 && (
                            <button 
                                className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider bg-rose-600 text-white shadow-sm hover:bg-rose-700 transition-all focus:outline-none" 
                                onClick={handleDeleteSelected} 
                                disabled={isDeleting}
                            >
                                {isDeleting ? (
                                    <>
                                        <span className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
                                        Deleting...
                                    </>
                                ) : (
                                    <>
                                        <FaTrash /> Delete Selected ({selectedIds.length})
                                    </>
                                )}
                            </button>
                        )}
                        <div className="relative">
                            <FaSearch className="absolute left-3.5 top-1/2 -translate-y-1/2 text-xs text-gray-400" />
                            <input 
                                type="text" 
                                placeholder="Search products..." 
                                value={searchTerm} 
                                onChange={(e) => setSearchTerm(e.target.value)} 
                                className="pl-9 pr-4 py-2 rounded-xl bg-white border border-gray-200 text-xs font-semibold outline-none focus:border-[#3D3F96] focus:ring-1 focus:ring-[#3D3F96]/30 transition-all w-56"
                            />
                        </div>
                    </div>
                </div>

                {/* Table Scrollable Wrapper */}
                <div className="overflow-x-auto">
                    <table className="w-full text-sm min-w-[1000px] table-auto align-middle">
                        <thead>
                            <tr className="text-[11px] font-bold uppercase tracking-wider text-gray-400 bg-gray-50/50 border-b border-gray-100">
                                <th className="text-center px-6 py-4 w-16">
                                    <input 
                                        type="checkbox" 
                                        onChange={handleSelectAll} 
                                        checked={sortedProducts.length > 0 && selectedIds.length === sortedProducts.length} 
                                        className="w-4 h-4 text-[#3D3F96] bg-gray-50 border-gray-200 rounded focus:ring-1 focus:ring-[#3D3F96]/30 cursor-pointer accent-[#3D3F96]"
                                        title="Select All"
                                    />
                                </th>
                                {visibleHeaders.map((header) => (
                                    <th 
                                        key={header.key} 
                                        className={`px-6 py-4 text-left ${header.sortable ? 'cursor-pointer select-none hover:text-slate-800' : ''}`} 
                                        onClick={() => header.sortable && handleSort(header.key)} 
                                    >
                                        <div className="flex items-center gap-1">
                                            {header.label}
                                            {header.sortable && sortColumn === header.key && (
                                                <span className="text-[10px]">{sortDirection === 'asc' ? '↑' : '↓'}</span>
                                            )}
                                        </div>
                                    </th>
                                ))}
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-50">
                            {sortedProducts.length > 0 ? (
                                sortedProducts.map((row) => {
                                    const isEditing = editingRow === row._id;
                                    return (
                                        <tr 
                                            key={row._id} 
                                            className={`transition-colors duration-150 ${isEditing ? 'bg-amber-50/40 hover:bg-amber-50/50' : 'hover:bg-gray-50/60'}`}
                                            onClick={() => !isEditing && handleRowClick(row)}
                                            style={{ cursor: isEditing ? 'default' : 'pointer' }}
                                        >
                                            <td className="px-6 py-4 text-center align-middle" onClick={(e) => e.stopPropagation()}>
                                                <input 
                                                    type="checkbox" 
                                                    onChange={() => handleSelectRow(row._id)} 
                                                    checked={selectedIds.includes(row._id)}
                                                    className="w-4 h-4 text-[#3D3F96] bg-gray-50 border-gray-200 rounded focus:ring-1 focus:ring-[#3D3F96]/30 cursor-pointer accent-[#3D3F96]"
                                                />
                                            </td>
                                            {visibleHeaders.map((header) => (
                                                <td key={header.key} className="px-6 py-4 align-middle">
                                                    {renderCellContent(header.key, row[header.key], isEditing, row)}
                                                </td>
                                            ))}
                                        </tr>
                                    );
                                })
                            ) : (
                                <tr>
                                    <td colSpan={visibleHeaders.length + 1} className="px-6 py-16 text-center">
                                        <div className="flex flex-col items-center justify-center gap-3">
                                            <div className="w-16 h-16 rounded-full bg-slate-50 flex items-center justify-center text-slate-300">
                                                <FaInbox className="text-3xl" />
                                            </div>
                                            <div>
                                                <h4 className="text-sm font-bold text-slate-700">No Medicine Products Found</h4>
                                                <p className="text-xs text-slate-400 mt-1">Import products by uploading an Excel sheet or updating your DB.</p>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* 4. DETAILS MODAL PANEL */}
            {modalShow && selectedMedicine && (
                <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 overflow-y-auto animate-in fade-in duration-200">
                    <div className="bg-white rounded-3xl w-full max-w-5xl max-h-[90vh] overflow-y-auto shadow-2xl border border-gray-100 p-6 relative flex flex-col gap-6 select-none animate-in zoom-in-95 duration-200">
                        
                        {/* Modal Header */}
                        <div className="flex items-center justify-between border-b border-gray-100 pb-4 shrink-0">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-xl bg-[#3D3F96]/15 text-[#3D3F96] flex items-center justify-center shrink-0">
                                    <FaBarcode className="text-lg" />
                                </div>
                                <div>
                                    <h3 className="text-lg font-black tracking-tight text-gray-800">{selectedMedicine.name || 'Medicine Details'}</h3>
                                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mt-0.5">DB-ID: {selectedMedicine.Id || selectedMedicine._id}</span>
                                </div>
                            </div>
                            <button 
                                onClick={() => setModalShow(false)}
                                className="w-8 h-8 rounded-lg bg-gray-50 hover:bg-gray-100 text-gray-400 flex items-center justify-center transition-colors focus:outline-none"
                            >
                                <FaTimes />
                            </button>
                        </div>

                        {/* Modal Body Scroll Area */}
                        <div className="space-y-6 overflow-y-auto">
                            {/* Medicine Images Carousel */}
                            <div className="flex justify-center bg-gray-50/50 rounded-2xl border border-gray-100/60 p-4">
                                {Array.isArray(selectedMedicine.image_url) && selectedMedicine.image_url.length > 0 ? (
                                    <div className="relative w-full max-w-lg h-64 overflow-hidden rounded-xl bg-white shadow-sm border border-gray-50 flex items-center justify-center">
                                        <img 
                                            src={selectedMedicine.image_url[0]} 
                                            alt={selectedMedicine.name} 
                                            className="max-h-full max-w-full object-contain"
                                            onError={handleImageError} 
                                        />
                                    </div>
                                ) : (
                                    <div className="relative w-full max-w-lg h-64 overflow-hidden rounded-xl bg-white shadow-sm border border-gray-50 flex items-center justify-center">
                                        <img 
                                            src={dummyImages[0]} 
                                            alt={selectedMedicine.name} 
                                            className="max-h-full max-w-full object-contain"
                                            onError={handleImageError} 
                                        />
                                    </div>
                                )}
                            </div>

                            {/* Medical Detailed Grid */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div className="bg-white rounded-2xl border border-gray-100 p-5 shadow-sm space-y-4">
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Description</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.description || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Introduction</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.introduction || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>How It Works</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.how_works || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Benefits</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.benefits || 'N/A'}</p>
                                    </div>
                                </div>

                                <div className="bg-white rounded-2xl border border-gray-100 p-5 shadow-sm space-y-4">
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Storage</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.storage || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Usage / Indication</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.use_of || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>How To Use</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.how_to_use || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Side Effects</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.side_effect || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Safety Advice</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.safety_advise || 'N/A'}</p>
                                    </div>
                                    <div>
                                        <h4 className={`text-xs font-bold uppercase tracking-wider ${themeText}`}>Supervision</h4>
                                        <p className="text-xs text-gray-600 mt-1 leading-relaxed">{selectedMedicine.supervision || 'N/A'}</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Modal Footer */}
                        <div className="flex items-center justify-end gap-2 border-t border-gray-100 pt-4 shrink-0">
                            <button 
                                type="button" 
                                onClick={() => setModalShow(false)}
                                className="px-5 py-2.5 rounded-xl border border-gray-200 text-gray-600 hover:bg-gray-50 text-xs font-bold uppercase tracking-wider transition-all focus:outline-none"
                            >
                                Close
                            </button>
                            {selectedMedicine.url && (
                                <a 
                                    href={selectedMedicine.url} 
                                    target="_blank" 
                                    rel="noopener noreferrer" 
                                    className={`flex items-center gap-1.5 text-white font-bold px-5 py-2.5 rounded-xl text-xs uppercase tracking-wider transition-all focus:outline-none ${themeBg} ${themeHoverBg}`}
                                >
                                    View Source <FaArrowRight />
                                </a>
                            )}
                        </div>

                    </div>
                </div>
            )}
        </div>
    );
}